In [113]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [114]:
df = pd.read_excel('Plazas.xlsx')
df.head(5)

,Fecha Origen,Nombre,Telefono,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,2025-05-06 18:30:00,Alejandro Fernandez,NaN,AION,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Recibe recurso a finales de junio, proyección ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-05-06 18:00:00,David Israel,NaN,EMKOO,JOSE EDUARDO PARADA DURAN,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Finalizado,Si hay seguimiento,Dejo de contestar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-05-06 13:50:00,Rosendo Ceron,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-05-06 13:47:00,Fausto Ochoa Martinez,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-05-06 13:43:00,Brigida Lara Perez,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
df = pd.read_excel('Plazas.xlsx')
df.tail(5)

,Fecha Origen,Nombre,Telefono,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
1048569,2025-06-09 15:30:00,Miguel Fernandez,NaN,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048570,2025-06-09 13:15:00,Luis,NaN,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,GALERIAS TLAXCALA,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,2025-06-09 13:14:00,Rolando Manrique,NaN,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,2025-06-09 12:50:00,Odilia Cuamatzi Bautista,NaN,GS8,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,2025-05-24 12:19:22,Raul Jimenez,NaN,EMZOOM,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,Esta preautorizado,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
valores_nulos = df.isnull().sum()
valores_nulos

Fecha Origen                                1048272
Nombre                                      1048271
Telefono                                    1048574
Producto                                    1048271
Asesor                                      1048271
Origen                                      1048271
Seguimiento                                       7
Cita efetiva                                     10
PDM                                              11
SDC                                              11
Estatus                                           7
¿Por que no hay seguimiento?                1048375
¿Por que no ha visitado la agencia?         1048405
¿Por que no hubo prueba de manejo ?         1048546
¿Por que no hubo solicitud de credito?      1048547
¿Por que no se ha formalizado la compra?    1048560
Unnamed: 16                                 1048550
Unnamed: 17                                 1048574
Unnamed: 18                                 1048574
Unnamed: 19                                 1048573
dtype: int64

In [117]:
#Se eliminaron columnas innecesarias
df1= df.drop(['Telefono', 'Unnamed: 16','Unnamed: 17','Unnamed: 18', 'Unnamed: 19' ], axis=1)
df1

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?
0,2025-05-06 18:30:00,Alejandro Fernandez,AION,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Recibe recurso a finales de junio, proyección ...",NaN,NaN,NaN
1,2025-05-06 18:00:00,David Israel,EMKOO,JOSE EDUARDO PARADA DURAN,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Finalizado,Si hay seguimiento,Dejo de contestar,NaN,NaN,NaN
2,2025-05-06 13:50:00,Rosendo Ceron,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN
3,2025-05-06 13:47:00,Fausto Ochoa Martinez,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN
4,2025-05-06 13:43:00,Brigida Lara Perez,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,2025-06-09 15:30:00,Miguel Fernandez,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN
1048570,2025-06-09 13:15:00,Luis,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,GALERIAS TLAXCALA,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN
1048571,2025-06-09 13:14:00,Rolando Manrique,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN
1048572,2025-06-09 12:50:00,Odilia Cuamatzi Bautista,GS8,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN
1048573,2025-05-24 12:19:22,Raul Jimenez,EMZOOM,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,Esta preautorizado,NaN,NaN,NaN

In [118]:
valores_nulos = df1.isnull().sum()
valores_nulos

Fecha Origen                                1048272
Nombre                                      1048271
Producto                                    1048271
Asesor                                      1048271
Origen                                      1048271
Seguimiento                                       7
Cita efetiva                                     10
PDM                                              11
SDC                                              11
Estatus                                           7
¿Por que no hay seguimiento?                1048375
¿Por que no ha visitado la agencia?         1048405
¿Por que no hubo prueba de manejo ?         1048546
¿Por que no hubo solicitud de credito?      1048547
¿Por que no se ha formalizado la compra?    1048560
dtype: int64

In [119]:
df.shape

(1048574, 20)

In [120]:
df2 = df1.iloc[0:280, 0:20]
df3 = df1.iloc[1048550:1048576, 0:20]

In [121]:
df_final = pd.concat([df2, df3], ignore_index=True)

In [122]:
df_final

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?
0,2025-05-06 18:30:00,Alejandro Fernandez,AION,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Recibe recurso a finales de junio, proyección ...",NaN,NaN,NaN
1,2025-05-06 18:00:00,David Israel,EMKOO,JOSE EDUARDO PARADA DURAN,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Finalizado,Si hay seguimiento,Dejo de contestar,NaN,NaN,NaN
2,2025-05-06 13:50:00,Rosendo Ceron,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN
3,2025-05-06 13:47:00,Fausto Ochoa Martinez,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN
4,2025-05-06 13:43:00,Brigida Lara Perez,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,2025-06-09 15:30:00,Miguel Fernandez,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN
300,2025-06-09 13:15:00,Luis,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,GALERIAS TLAXCALA,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN
301,2025-06-09 13:14:00,Rolando Manrique,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN
302,2025-06-09 12:50:00,Odilia Cuamatzi Bautista,GS8,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN
303,2025-05-24 12:19:22,Raul Jimenez,EMZOOM,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,Esta preautorizado,NaN,NaN,NaN

In [123]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  4
Nombre                                        3
Producto                                      3
Asesor                                        3
Origen                                        3
Seguimiento                                   7
Cita efetiva                                  9
PDM                                          10
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [124]:
#Sustituir valores nulos por una fecha ficticia
df_final["Fecha Origen"] =df_final["Fecha Origen"].fillna("2030-06-19 00:00:00")

In [125]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        3
Producto                                      3
Asesor                                        3
Origen                                        3
Seguimiento                                   7
Cita efetiva                                  9
PDM                                          10
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [126]:
#Sustiruir valor nulo por texto 
df_final["Nombre"] =df_final["Nombre"].fillna("No se registro nombre")

In [127]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      3
Asesor                                        3
Origen                                        3
Seguimiento                                   7
Cita efetiva                                  9
PDM                                          10
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [128]:
#Sustiruir valor nulo por texto 
df_final["Producto"] =df_final["Producto"].fillna("No se registro producto")

In [129]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        3
Origen                                        3
Seguimiento                                   7
Cita efetiva                                  9
PDM                                          10
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [130]:
#Sustiruir valor nulo por texto 
df_final["Asesor"] =df_final["Asesor"].fillna("No se registro Asesor")

In [131]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        3
Seguimiento                                   7
Cita efetiva                                  9
PDM                                          10
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [132]:
#Sustiruir valor nulo por texto 
df_final["Origen"] =df_final["Origen"].fillna("No hay registro")

In [133]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        0
Seguimiento                                   7
Cita efetiva                                  9
PDM                                          10
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [134]:
#Sustiruir valor nulo por texto 
df_final["Seguimiento"] =df_final["Seguimiento"].fillna("No hay registro")

In [135]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        0
Seguimiento                                   0
Cita efetiva                                  9
PDM                                          10
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [136]:
#Sustiruir valor nulo por texto 
df_final["Cita efetiva "] =df_final["Cita efetiva "].fillna("No se registro")

In [137]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        0
Seguimiento                                   0
Cita efetiva                                  0
PDM                                          10
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [138]:
#Sustiruir valor nulo por texto 
df_final["PDM"] =df_final["PDM"].fillna("No se registro")

In [139]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        0
Seguimiento                                   0
Cita efetiva                                  0
PDM                                           0
SDC                                           9
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [140]:
#Sustiruir valor nulo por texto 
df_final["SDC"] =df_final["SDC"].fillna("No se registro")

In [141]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        0
Seguimiento                                   0
Cita efetiva                                  0
PDM                                           0
SDC                                           0
Estatus                                       7
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [142]:
#Sustiruir valor nulo por texto 
df_final["Estatus"] =df_final["Estatus"].fillna("No hay registro")

In [143]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        0
Seguimiento                                   0
Cita efetiva                                  0
PDM                                           0
SDC                                           0
Estatus                                       0
¿Por que no hay seguimiento?                107
¿Por que no ha visitado la agencia?         136
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
dtype: int64

In [155]:
#Sustiruir valor nulo por texto 
df_final["¿Por que no hay seguimiento?"] =df_final["¿Por que no hay seguimiento?"].fillna("No hay registro") 
df_final["¿Por que no ha visitado la agencia?"] =df_final["¿Por que no ha visitado la agencia?"].fillna("No hay registro") 
df_final["¿Por que no hubo prueba de manejo ?"] =df_final["¿Por que no hubo prueba de manejo ?"].fillna("No hay registro") 
df_final["¿Por que no hubo solicitud de credito?"] =df_final["¿Por que no hubo solicitud de credito?"].fillna("No hay registro") 
df_final["¿Por que no se ha formalizado la compra?"] =df_final["¿Por que no se ha formalizado la compra?"].fillna("No hay registro")

In [156]:
valores_nulos = df_final.isnull().sum()
valores_nulos

Fecha Origen                                0
Nombre                                      0
Producto                                    0
Asesor                                      0
Origen                                      0
Seguimiento                                 0
Cita efetiva                                0
PDM                                         0
SDC                                         0
Estatus                                     0
¿Por que no hay seguimiento?                0
¿Por que no ha visitado la agencia?         0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo solicitud de credito?      0
¿Por que no se ha formalizado la compra?    0
dtype: int64

In [157]:
#Convertir DataFrame a CSV
df_final.to_csv("Plazas_SinNulos.csv")