In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
df = pd.read_excel('Base_de_Leads.xlsx')
df.head(5)

,Fecha de Alta,Mes Lead,AgLead,Titulo,Nombre,Telefono,Correo,Producto,Temperatura,Comentario,Asesor,Fuente,Origen,
0,2025-11-30 08:38:00,11,834956f716e7ddae82527bf81c29ebc8,Lead ANGE,Apolonio Torres Perez,NaN,NaN,EMZOOM,Lead Muy Interesado,Se reactiva lead para captura de ventaFinal:EM...,CESAR DE JESUS PESTAÃ‘A,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,1 Ventas
1,2025-11-29 21:17:00,11,13ee2f21ed8506825e8591bf1abdab51,Lead ANGE,Javier Nieto,NaN,NaN,GS4 MAX,Lead Interes Medio,SE LE CONTACTA EN PLAZA ANGELOPOLIS Final:GS4 ...,MAURICIO ALFREDO VAZQUEZ FARFAN,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Finalizado
2,2025-11-29 20:48:00,11,fad33b39f526b4ebe04a4b7e86002d5a,Lead ANGE,Ismael Segovia Banos,NaN,NaN,GS4 MAX,Lead Muy Interesado,SE INTERESA POR GS4 Final:GS4 MAX HEV,MAURICIO ALFREDO VAZQUEZ FARFAN,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,1 Ventas
3,2025-11-29 16:11:00,11,e495cd540b7c7dc55b516fbdc7ea8bf0,Lead ANGE,Luis Jaime Estrada,NaN,NaN,EMKOO,Lead Muy Interesado,ofrecÃ­ tambiÃ©n GS4 y emko hv Pidieron:EMKOO HEV,RICARDO SILVA HERAS,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Contactado
4,2025-11-29 16:08:00,11,4d2b212032284fa42fa64a493e34c4ed,Lead ANGE,Hector Hamley,NaN,NaN,EMKOO,Lead Interes Medio,interÃ©s Pidieron:EMKOO HEV,RICARDO SILVA HERAS,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Contactado

In [14]:
valores_nulos = df.isnull().sum()
valores_nulos

Fecha de Alta      0
Mes Lead           0
AgLead             0
Titulo             0
Nombre             0
Telefono         210
Correo           210
Producto          14
Temperatura        0
Comentario         0
Asesor             0
Fuente             0
Origen             0
                   0
dtype: int64

In [ ]:
#Se eliminaron columnas innecesarias
df1= df.drop(['Telefono','Correo'], axis=1)
df1

,Fecha de Alta,Mes Lead,AgLead,Titulo,Nombre,Producto,Temperatura,Comentario,Asesor,Fuente,Origen,
0,2025-11-30 08:38:00,11,834956f716e7ddae82527bf81c29ebc8,Lead ANGE,Apolonio Torres Perez,EMZOOM,Lead Muy Interesado,Se reactiva lead para captura de ventaFinal:EM...,CESAR DE JESUS PESTAÃ‘A,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,1 Ventas
1,2025-11-29 21:17:00,11,13ee2f21ed8506825e8591bf1abdab51,Lead ANGE,Javier Nieto,GS4 MAX,Lead Interes Medio,SE LE CONTACTA EN PLAZA ANGELOPOLIS Final:GS4 ...,MAURICIO ALFREDO VAZQUEZ FARFAN,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Finalizado
2,2025-11-29 20:48:00,11,fad33b39f526b4ebe04a4b7e86002d5a,Lead ANGE,Ismael Segovia Banos,GS4 MAX,Lead Muy Interesado,SE INTERESA POR GS4 Final:GS4 MAX HEV,MAURICIO ALFREDO VAZQUEZ FARFAN,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,1 Ventas
3,2025-11-29 16:11:00,11,e495cd540b7c7dc55b516fbdc7ea8bf0,Lead ANGE,Luis Jaime Estrada,EMKOO,Lead Muy Interesado,ofrecÃ­ tambiÃ©n GS4 y emko hv Pidieron:EMKOO HEV,RICARDO SILVA HERAS,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Contactado
4,2025-11-29 16:08:00,11,4d2b212032284fa42fa64a493e34c4ed,Lead ANGE,Hector Hamley,EMKOO,Lead Interes Medio,interÃ©s Pidieron:EMKOO HEV,RICARDO SILVA HERAS,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Contactado
...,...,...,...,...,...,...,...,...,...,...,...,...
205,2025-11-03 17:27:00,11,6a3ea80eb04d295f086c78b21c4f3b7a,Lead ANGE,Celestino Garcia,EMZOOM,Lead Interes Medio,va a vender su i10Pidieron:EMZOOM,OMAR HERNANDEZ GARCIA,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Finalizado
206,2025-11-03 17:27:00,11,e3bfbfe06043bf02d562037edded5de6,Lead ANGE,Alvaro Delgadillo,EMZOOM,Lead Interes Medio,Se reactiva lead para captura de citaFinal:EMZOOM,Alan GonzÃ¡lez Belanzate,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Finalizado
207,2025-11-03 13:36:00,11,95bb2e63079be46c032e83459f0e9a90,Lead ANGE,Eden Castallon,EMZOOM,Lead Interes Medio,Interes EMZOOM Pidieron:EMZOOM,Alan GonzÃ¡lez Belanzate,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Finalizado
208,2025-11-02 12:44:00,11,801ce20ce803347f8cd9bb4239a679b2,Lead ANGE,Eduardo Cervantes,EMZOOM,Lead Interes Medio,se envÃ­a informaciÃ³n Pidieron:EMZOOM,Pedro GonzÃ¡les EspÃ­ndol,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Contactado
209,2025-11-02 12:09:00,11,d81245e7b9dfcbc9487cb0f6bbe7fd1f,Lead ANGE,Jose Carlos Cruz,EMZOOM,Lead Interes Medio,se envÃ­a cotizaciÃ³n de autoPidieron:EMZOOM,Pedro GonzÃ¡les EspÃ­ndol,11.Origen Personalizado/Calle,PLAZA ANGELOPOLIS,Finalizado

In [38]:
valores_nulos = df1.isnull().sum()
valores_nulos

Fecha de Alta     0
Mes Lead          0
AgLead            0
Titulo            0
Nombre            0
Producto         14
Temperatura       0
Comentario        0
Asesor            0
Fuente            0
Origen            0
                  0
dtype: int64

In [41]:
#se sustituyeron los valores nulos de producto por texto de "No se registro producto"
df1["Producto"] =df1["Producto"].fillna("No se registro producto")

In [42]:
valores_nulos = df1.isnull().sum()
valores_nulos

Fecha de Alta    0
Mes Lead         0
AgLead           0
Titulo           0
Nombre           0
Producto         0
Temperatura      0
Comentario       0
Asesor           0
Fuente           0
Origen           0
                 0
dtype: int64

In [43]:
#Convertir DataFrame a CSV
df1.to_csv("Base_de_Leads_SinNulos.csv")