In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
df = pd.read_csv('Citas_Digital_Filtrado.csv')
df.head(5)

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

In [21]:
#Se eliminaron columnas innecesarias (Unnamed:15)
df1= df.drop(['Unnamed: 15'], axis=1)
df1

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,Ana,2026-07-22,Maira Escalante,NaN,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07-22,Zaira Macip,NaN,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
673,Ignacio,2026-07-27,Julio Hernandez,NaN,Activo,0.5,1.0,0.0,0.0,Victor,NaN,NaN,NaN,NaN,NaN
674,Ignacio,2026-07-24,Xhunaxhi Vicente,NaN,Activo,1,1.0,1.0,1.0,Ignacio,NaN,NaN,NaN,NaN,NaN
675,Ignacio,2026-07-29,DR Jairo Rodriguez Farias,NaN,Activo,1,1.0,1.0,1.0,Victor,NaN,NaN,NaN,NaN,NaN

In [22]:
valores_nulos = df.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [23]:
df2 = df1.copy()

In [24]:
#Se sustituyeron los valores nulos por valores no nulos hacia adelante 
df2["BDC "] = df2["BDC "].ffill()

In [25]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [26]:
#Se sustiuyo valores nulos por una fecha ficticia
df2["Fecha"] =df2["Fecha"].fillna("2030-06-19 00:00:00")

In [27]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [28]:
#Se sustituyeron los valores nulos por valores no nulos hacia adelante 
df2["Nombre Cliente "] = df2["Nombre Cliente "].ffill()

In [29]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [30]:
#se sustituyeron los valores nulos de telefono por texto de "no identificado"
df2["Telefono "] =df2["Telefono "].fillna("No identificado")

In [31]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [32]:
#Se sustituyeron los valores nulos por valores no nulos hacia adelante 
df2["Estatus de Lead"] = df2["Estatus de Lead"].ffill()

In [33]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [34]:
#se cambiaron los valores a float
df2['Potencial de compra'].unique

df2['Potencial de compra']=df2['Potencial de compra'].astype("string")
df2['Potencial de compra']=df2['Potencial de compra'].str.replace("Ventas ","0", regex=False)
df2['Potencial de compra']=df2['Potencial de compra'].str.replace("%","", regex=False)
df2['Potencial de compra']=df2['Potencial de compra'].str.replace("'","", regex=False)
df2['Potencial de compra']=df2['Potencial de compra'].str.replace("&","", regex=False)

df2['Potencial de compra']=df2['Potencial de compra'].astype(float)

In [ ]:
#Sustituir valores nulos con promedio o media
df2["Potencial de compra"]=df2["Potencial de compra"].fillna(round(df2["Potencial de compra"].mean(),1))

In [36]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [ ]:
#Sustituir valores nulos con promedio o media
df2["Venta"]=df2["Venta"].fillna(round(df2["Venta"].mean(),1))

In [40]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         0
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [42]:
#se sustituyeron los valores nulos de Asesor por texto de "Asesor no identificado"
df2["Asesor Asignado"] =df2["Asesor Asignado"].fillna("Asesor no identificado")

In [44]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [45]:
#se sustituyeron los valores nulos de ¿Por que no ha visitado la agencia? por texto de "No resgistro razón"
df2["¿Por que no ha visitado la agencia?"] =df2["¿Por que no ha visitado la agencia?"].fillna("No resgistro razón")

In [46]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [47]:
#se sustituyeron los valores nulos de ¿Por que no hay solicitud de credito? por texto de "No resgistro razón"
df2["¿Por que no hay solicitud de credito?"] =df2["¿Por que no hay solicitud de credito?"].fillna("No resgistro razón")

In [48]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [49]:
#se sustituyeron los valores nulos de ¿Por que no hubo prueba de manejo ? por texto de "No resgistro razón"
df2["¿Por que no hubo prueba de manejo ?"] =df2["¿Por que no hubo prueba de manejo ?"].fillna("No resgistro razón")

In [50]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?           0
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [52]:
#se sustituyeron los valores nulos de ¿Por que no hubo proceso wow? por texto de "No resgistro razón"
df2["¿Por que no hubo proceso wow?"] =df2["¿Por que no hubo proceso wow?"].fillna("No resgistro razón")

In [53]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Telefono                                      0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?           0
¿Por que no hubo proceso wow?                 0
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [55]:
#se sustituyeron los valores nulos de ¿Por que se asigno antes de vistar piso?  por texto de "No resgistro razón"
df2["¿Por que se asigno antes de vistar piso?"] =df2["¿Por que se asigno antes de vistar piso?"].fillna("No resgistro razón")

In [56]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         1
SDC                                         2
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [59]:
#Sustituir valores nulos con promedio o media
df2["SDC"]=df2["SDC"].fillna(round(df2["SDC"].median(),1))

In [60]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         1
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [61]:
#Sustituir valores nulos con promedio o media
df2["PDM"]=df2["PDM"].fillna(round(df2["PDM"].median(),1))

In [62]:
valores_nulos = df2.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       660 non-null    str
 1   Fecha                                     75 non-null     str
 2   Nombre Cliente                            655 non-null    str
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           641 non-null    str
 5   Potencial de compra                       602 non-null    str
 6   PDM                                       675 non-null    float64
 7   SDC                                       674 non-null    float64
 8   Venta                                     671 non-null    float64
 9   Asesor Asignado                           644 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: float64(3), str(13)
memory usage: 84.6 KB

In [64]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       676 non-null    str
 1   Fecha                                     676 non-null    str
 2   Nombre Cliente                            676 non-null    str
 3   Telefono                                  676 non-null    str
 4   Estatus de Lead                           676 non-null    str
 5   Potencial de compra                       676 non-null    float64
 6   PDM                                       676 non-null    float64
 7   SDC                                       676 non-null    float64
 8   Venta                                     676 non-null    float64
 9   Asesor Asignado                           676 non-null    str
 10  ¿Por que no ha visitado la agencia?       676 non-null    str
 11  ¿Por que no hay solicitud de credito?     676 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       676 non-null    str
 13  ¿Por que no hubo proceso wow?             676 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  676 non-null    str
dtypes: float64(4), str(11)
memory usage: 79.3 KB

In [66]:
#Convertir DataFrame a CSV
df2.to_csv("Citas_Digital_Filtrado2.csv")